---
XE-1:
    hostname: 192.168.122.2
    port: 22
    username: cisco
    password: cisco
    platform: ios
    groups:
        - xe-routers

NX-2:
    hostname: 192.168.122.3
    port: 443
    username: cisco
    password: cisco
    platform: ios
    groups:
        - nx-routers  